spring:
  application:
    name: humus
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 3000

resilience4j:
  retry:
    instances:
      external-order:
        max-attempts: 3
        wait-duration: 2s
        retry-exceptions:
          - feign.FeignException.InternalServerError
          - feign.RetryableException
external:
  service:
    endpoint: https://external-service.com

